name: eutonafila_frontend
description: A Flutter web application for queue management system

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  flutter_map_cancellable_tile_provider: ^3.1.0
  share_plus: ^7.2.1
  # API communication dependencies
  dio: ^5.4.0
  json_annotation: ^4.8.1
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  network_image_mock: ^2.1.1
  # Code generation for JSON serialization
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true