# Generated by Django 5.0.2 on 2025-04-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_entradafila_options_and_more'),
        ('domain', '0002_create_website_builder_models'),
    ]

    operations = [
    ]
