# Generated by Django 5.0.2 on 2025-04-24 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cores', models.JSONField(default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('horario_abertura', models.TimeField(default='09:00')),
                ('horario_fechamento', models.TimeField(default='18:00')),
                ('dias_funcionamento', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.IntegerField(help_text='Duração em minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='domain.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaFila',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horario_atendimento', models.DateTimeField(blank=True, null=True)),
                ('horario_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.barbearia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.servico')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
