# Generated by Django 5.0.2 on 2025-04-24 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradafila',
            options={'ordering': ['-prioridade', 'created_at']},
        ),
        migrations.AddField(
            model_name='barbearia',
            name='enable_priority_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='max_capacity',
            field=models.IntegerField(default=10, help_text='Maximum number of clients in waiting queue'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP status for priority queue'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_visits',
            field=models.IntegerField(default=0, help_text='Total number of completed services'),
        ),
        migrations.AddField(
            model_name='entradafila',
            name='estimativa_duracao',
            field=models.IntegerField(default=0, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='entradafila',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entradafila',
            name='notified',
            field=models.BooleanField(default=False, help_text='Whether client has been notified'),
        ),
        migrations.AddField(
            model_name='entradafila',
            name='position_number',
            field=models.IntegerField(default=0, help_text='Position number for display'),
        ),
        migrations.AddField(
            model_name='entradafila',
            name='prioridade',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'VIP')], default=0),
        ),
        migrations.AddField(
            model_name='entradafila',
            name='time_in_queue',
            field=models.IntegerField(default=0, help_text='Time spent in queue in minutes'),
        ),
        migrations.AddField(
            model_name='servico',
            name='complexity',
            field=models.IntegerField(choices=[(1, 'Simple'), (2, 'Medium'), (3, 'Complex')], default=1, help_text='Service complexity factor'),
        ),
        migrations.AddField(
            model_name='servico',
            name='popularity',
            field=models.IntegerField(default=0, help_text='Popularity score based on service frequency'),
        ),
        migrations.AlterField(
            model_name='entradafila',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('ausente', 'Ausente')], default='aguardando', max_length=20),
        ),
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_break', 'On Break'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('status_since', models.DateTimeField(auto_now=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbeiros', to='domain.barbearia')),
                ('especialidades', models.ManyToManyField(blank=True, related_name='barbeiros_especializados', to='domain.servico')),
            ],
        ),
        migrations.AddField(
            model_name='entradafila',
            name='barbeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.barbeiro'),
        ),
    ]
