# Generated by Django 5.0.2 on 2025-05-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='layouts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('about', 'About Us'), ('services', 'Services'), ('team', 'Team'), ('gallery', 'Gallery'), ('testimonials', 'Testimonials'), ('contact', 'Contact')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_path', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='domain.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='domain.barbearia')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BarbeariaCustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbearia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_page', to='domain.barbearia')),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbershop_pages', to='domain.pagelayout')),
            ],
        ),
        migrations.CreateModel(
            name='ActivePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.barbeariacustompage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.pagesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='barbeariacustompage',
            name='active_sections',
            field=models.ManyToManyField(through='domain.ActivePageSection', to='domain.pagesection'),
        ),
    ] 