# Generated by Django 5.0.2 on 2025-05-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='layouts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_path', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.RemoveField(
            model_name='entradafila',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='entradafila',
            name='barbearia',
        ),
        migrations.RemoveField(
            model_name='entradafila',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='barbearia',
        ),
        migrations.AlterModelOptions(
            name='barbearia',
            options={'verbose_name': 'Barbearia', 'verbose_name_plural': 'Barbearias'},
        ),
        migrations.RemoveField(
            model_name='barbearia',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='barbearia',
            name='logo',
        ),
        migrations.AddField(
            model_name='barbearia',
            name='enable_priority_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='max_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='horario_abertura',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='horario_fechamento',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BarbeariaCustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbearia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_page', to='domain.barbearia')),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbershop_pages', to='domain.pagelayout')),
            ],
        ),
        migrations.CreateModel(
            name='ActivePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.barbeariacustompage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.pagesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='domain.barbearia')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='barbeariacustompage',
            name='active_sections',
            field=models.ManyToManyField(through='domain.ActivePageSection', to='domain.pagesection'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='domain.barbearia')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='EntradaFila',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
