# Generated by Django 5.0.2 on 2025-04-25 09:10

from django.db import migrations


def create_initial_website_builder_data(apps, schema_editor):
    """
    Create initial data for PageLayout and PageSection models
    """
    # Get models
    PageLayout = apps.get_model('domain', 'PageLayout')
    PageSection = apps.get_model('domain', 'PageSection')
    
    # Create default layout
    default_layout = PageLayout.objects.create(
        name='Default Layout',
        description='Default layout with standard sections',
        is_active=True
    )
    
    # Create page sections
    sections = [
        {
            'name': 'Hero Banner',
            'section_type': 'hero',
            'description': 'Main banner with title, subtitle and call-to-action button',
            'template_path': 'sections/hero.html',
            'is_required': True,
            'order_index': 0,
        },
        {
            'name': 'Services',
            'section_type': 'services',
            'description': 'Display barbershop services',
            'template_path': 'sections/services.html',
            'is_required': True,
            'order_index': 1,
        },
        {
            'name': 'About Us',
            'section_type': 'about',
            'description': 'Information about the barbershop',
            'template_path': 'sections/about.html',
            'is_required': False,
            'order_index': 2,
        },
        {
            'name': 'Team',
            'section_type': 'team',
            'description': 'Display information about the team of barbers',
            'template_path': 'sections/team.html',
            'is_required': False,
            'order_index': 3,
        },
        {
            'name': 'Gallery',
            'section_type': 'gallery',
            'description': 'Photo gallery of the barbershop',
            'template_path': 'sections/gallery.html',
            'is_required': False,
            'order_index': 4,
        },
        {
            'name': 'Testimonials',
            'section_type': 'testimonials',
            'description': 'Customer testimonials',
            'template_path': 'sections/testimonials.html',
            'is_required': False,
            'order_index': 5,
        },
        {
            'name': 'Contact',
            'section_type': 'contact',
            'description': 'Contact information and form',
            'template_path': 'sections/contact.html',
            'is_required': False,
            'order_index': 6,
        },
    ]
    
    # Create page sections
    for section_data in sections:
        PageSection.objects.create(**section_data)


def remove_initial_website_builder_data(apps, schema_editor):
    """
    Remove initial data for PageLayout and PageSection models
    """
    # Get models
    PageLayout = apps.get_model('domain', 'PageLayout')
    PageSection = apps.get_model('domain', 'PageSection')
    
    # Delete all page sections
    PageSection.objects.all().delete()
    
    # Delete all page layouts
    PageLayout.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_merge_20250425_0904'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_website_builder_data,
            remove_initial_website_builder_data
        ),
    ] 