# Generated by Django 5.0.2 on 2025-04-24 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cores', models.JSONField(default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('horario_abertura', models.TimeField(default='09:00')),
                ('horario_fechamento', models.TimeField(default='18:00')),
                ('dias_funcionamento', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='barbeiros/')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('pausa', 'Em pausa'), ('ausente', 'Ausente')], default='disponivel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbearia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.IntegerField(help_text='Duração em minutos')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='barbershop.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('horario_chegada', models.DateTimeField(auto_now_add=True)),
                ('horario_atendimento', models.DateTimeField(blank=True, null=True)),
                ('horario_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbearia')),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.servico')),
            ],
        ),
    ]
