# Generated by Django 5.0.2 on 2025-05-03 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_add_max_capacity_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fila',
            options={'ordering': ['horario_chegada']},
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='especialidades',
            field=models.ManyToManyField(related_name='barbeiros_especializados', to='barbershop.servico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fila',
            name='estimativa_duracao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fila',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fila',
            name='position_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servico',
            name='complexity',
            field=models.IntegerField(blank=True, choices=[(1, 'SIMPLE'), (2, 'MEDIUM'), (3, 'COMPLEX')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='popularity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('busy', 'BUSY'), ('break', 'BREAK'), ('offline', 'OFFLINE')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fila',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'NORMAL'), (2, 'BRONZE'), (3, 'SILVER'), (4, 'GOLD'), (5, 'VIP')], default=1),
        ),
        migrations.AlterField(
            model_name='fila',
            name='status',
            field=models.CharField(choices=[('waiting', 'AGUARDANDO'), ('in_service', 'ATENDIMENTO'), ('completed', 'FINALIZADO'), ('cancelled', 'CANCELADO'), ('no_show', 'AUSENTE')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
