# Generated by Django 5.0.2 on 2025-05-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_alter_fila_options_barbeiro_especialidades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fila',
            options={'ordering': ['position_number', 'created_at']},
        ),
        migrations.AddField(
            model_name='fila',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fila',
            name='estimated_wait_time',
            field=models.IntegerField(default=0, help_text='Estimated wait time in minutes'),
        ),
        migrations.AddField(
            model_name='fila',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='barbeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='barbershop.barbeiro'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
