# Generated by Django 5.0.2 on 2025-05-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_remove_entradafila_barbeiro_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='PRAGMA foreign_keys=OFF;',
            reverse_sql='PRAGMA foreign_keys=ON;'
        ),
    ] 