name: Build-and-push to ACR (fast path)

on:
  push:
    branches: [ main ]
    paths:
      - "backend/GrandeTech.QueueHub.API/**"
      - ".github/workflows/acr-build.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "backend/GrandeTech.QueueHub.API/**"
      - ".github/workflows/acr-build.yml"

env:
  ACR_NAME: acrqueuehubapi001               # registry name
  IMAGE_NAME: queuehub-api                  # repository in ACR
  DOCKERFILE: backend/GrandeTech.QueueHub.API/GrandeTech.QueueHub.API/Dockerfile
  CONTEXT: backend/GrandeTech.QueueHub.API  # build context folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # service-principal JSON

      - name: ACR build & push
        run: |
          az acr build \
            --registry   $ACR_NAME \
            --image      $IMAGE_NAME:${{ github.sha }} \
            --image      $IMAGE_NAME:latest \
            --file       $DOCKERFILE \
            $CONTEXT 